[Triggers]
;0 is false(off), 1 is true(on)

;enables knocking out npcs that don't see you and aren't in combat
BackBash = 1

;enables knocking out npcs that are bleeding out (near death) with bash
BleedoutBash = 1

;replaces the essential down status with a knockout
EssentialDown = 1

;knock out humanoids only
HumanoidsOnly = 1

[Status]
;duration of unconscious status, in hours
UnconsciousDuration = 4.0

;whether knocking innocent npcs out is a crime
IsCrime = 1

;whether unconscious NPCs are considered the same as dead by the game for different purposes: quests, detection, combat, etc. Recommended to keep on for vanilla compatibility unless it causes issues specifically.
;this setting cannot be hotloaded and the game must be relaunched after it changes. 
IsConsideredDead = 1