[Triggers]
;0 is false(off), 1 is true(on)

;enables knocking out npcs that don't see you and aren't in combat
BackBash = 1

;enables knocking out npcs that are bleeding out (near death) with bash
BleedoutBash = 1

;replaces the essential down status with a knockout
EssentialDown = 1

[Status]
;duration of unconscious status, in hours
UnconsciousDuration = 4.0

;whether knocking innocent npcs out is a crime
IsCrime = 1